# **NumPy Arrays**

In [1]:
import numpy as np

# **1 Basic Array Creation**

In [3]:
arr=np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [4]:
a=[1,2,3,4]
a

[1, 2, 3, 4]

In [ ]:
#numpy array same datatype store kore

In [5]:
aa=[1,2,3,4,'HI']

In [6]:
np.array(aa)

array(['1', '2', '3', '4', 'HI'], dtype='<U21')

In [9]:
l=[[1,2,3],[4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [10]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Array generation function

In [11]:
arr=np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
arr=np.zeros(9)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [15]:
arr=np.zeros((4,8))
arr

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [16]:
arr=np.ones(6)
arr

array([1., 1., 1., 1., 1., 1.])

In [18]:
arr=np.ones((4,8))
arr

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [21]:
arr=np.linspace(1,10,6)
arr

array([ 1. ,  2.8,  4.6,  6.4,  8.2, 10. ])

# Random Generation function

In [25]:
np.random.rand(5)  #(-1,1)

array([0.89995758, 0.2753838 , 0.68003384, 0.79192431, 0.71606763])

In [26]:
np.random.randn(5)  #(-3,3)

array([-0.60808446,  0.11879649, -1.97261839,  0.05560837,  0.03504021])

In [27]:
np.random.randint(6)

2

In [28]:
np.random.randint(10,20,2)

array([16, 14])

# Array Attributes

In [30]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [31]:
arr.shape

(3, 3)

In [32]:
arr.size

9

In [34]:
arr.dtype

dtype('int64')

# Array Methods

In [35]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [38]:
print(arr.min())

1


In [40]:
print(arr.max())

9


In [41]:
arr.sum()

np.int64(45)

In [42]:
np.sum(arr,axis=0)

array([12, 15, 18])

In [43]:
np.sum(arr,axis=1)

array([ 6, 15, 24])

In [44]:
arr.mean()

np.float64(5.0)

In [45]:
arr.std()

np.float64(2.581988897471611)

In [46]:
arr.argmax()

np.int64(8)

In [47]:
arr.argmin()

np.int64(0)

# Reshaping and Resizing

In [49]:
arr=np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [50]:
arr.reshape(5,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [51]:
arr=arr.reshape(5,6)
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

# **2 Arrays Indexing and Slicing**

# Numpy Indexing and Slicing of Vectors

In [53]:
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [54]:
arr[9]

np.int64(20)

In [55]:
arr[1:4]

array([12, 13, 14])

In [56]:
arr[:5]

array([11, 12, 13, 14, 15])

In [57]:
arr[3:]

array([14, 15, 16, 17, 18, 19, 20])

In [58]:
arr[::2]

array([11, 13, 15, 17, 19])

In [59]:
arr[1::2]

array([12, 14, 16, 18, 20])

In [61]:
arr_slice=arr[3::2]
arr_slice

array([14, 16, 18, 20])

#Numpy Indexing and Slicing of Matrix

In [86]:
arr=np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [64]:
arr[5]

array([26, 27, 28, 29, 30])

In [65]:
arr[0,0]

np.int64(1)

In [66]:
arr[0,4]

np.int64(5)

In [67]:
arr[0:2,1:3]

array([[2, 3],
       [7, 8]])

In [68]:
arr[3:6,3:5]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [69]:
arr[:,2]

array([ 3,  8, 13, 18, 23, 28])

# Boolean Indexing

In [70]:
arr=np.arange(11,21)

In [71]:
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [72]:
bool_index=arr>15
bool_index

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [74]:

arr[bool_index]

array([16, 17, 18, 19, 20])

In [75]:
bool_index=arr%2==0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [76]:
arr[bool_index]

array([12, 14, 16, 18, 20])

# **3 Array Operations**

# Arithmetic operation

In [78]:
a1=np.array([1,2,3,4,5])
a2=np.array([6,7,8,9,10])
a1+a2  #size same thakte hobe

array([ 7,  9, 11, 13, 15])

In [79]:
a1-a2

array([-5, -5, -5, -5, -5])

In [80]:
a1*a2

array([ 6, 14, 24, 36, 50])

In [81]:
a1/a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [82]:
a1//a2

array([0, 0, 0, 0, 0])

In [83]:
a1**a2

array([      1,     128,    6561,  262144, 9765625])

# Broadcasting

In [84]:
l=[10,20,30,40]
arr=np.array(l)

In [85]:
arr+10

array([20, 30, 40, 50])

In [89]:
arr=np.arange(1,31).reshape(6,5)
arr+10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40]])

# Deep and Shallow copy

In [91]:
arr=np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [93]:
slice=arr[0:5]
slice

array([1, 2, 3, 4, 5])

In [95]:
slice=slice+10
slice

array([21, 22, 23, 24, 25])

In [96]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [103]:
# slice korle alada location use kore.. main array te kuno change hoy na

In [97]:
b=arr

In [98]:
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [99]:
b[0]=99

In [100]:
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [101]:
arr

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [102]:
#direct rakle ekta te change korle rekta o change hoy

In [105]:
c=arr.copy()
c

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [108]:
c[0]=1
c

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [109]:
arr

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [110]:
#copy() use korle 2 ta alada location e thake

# Matrix Operations

In [112]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

In [113]:
A

array([[1, 2],
       [3, 4]])

In [114]:
B

array([[5, 6],
       [7, 8]])

In [115]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [116]:
A

array([[1, 2],
       [3, 4]])

In [117]:
A.T

array([[1, 3],
       [2, 4]])

# Advance Array Manipulation

In [118]:
#Stacking Array

In [119]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [120]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [121]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [123]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

# Splitting array

In [124]:
c = np.arange(16).reshape(4, 4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [125]:
np.hsplit(c,4)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [127]:
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [126]:
np.vsplit(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [129]:
a=np.vsplit(c,4)

In [130]:
a

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [131]:
for i in a:
  print(i)

[[0 1 2 3]]
[[4 5 6 7]]
[[ 8  9 10 11]]
[[12 13 14 15]]
